{
    "lists": [
        {
            "id": "901510966716",
            "name": "another list",
            "orderindex": 0,
            "content": "",
            "status": null,
            "priority": null,
            "assignee": null,
            "task_count": 0,
            "due_date": null,
            "start_date": null,
            "folder": {
                "id": "90156853247",
                "name": "test ID folder",
                "hidden": false,
                "access": true
            },
            "space": {
                "id": "90154548276",
                "name": "Team Space",
                "access": true
            },
            "archived": false,
            "override_statuses": false,
            "permission_level": "create"
        },
        {
            "id": "901510965829",
            "name": "Tesr List for del",
            "orderindex": 1,
            "content": "string generated by Postman: ut",
            "status": null,
            "priority": null,
            "assignee": null,
            "task_count": 0,
            "due_date": null,
            "start_date": null,
            "folder": {
                "id": "90156853247",
                "name": "test ID folder",
                "hidden": false,
                "access": true
            },
            "space": {
                "id": "90154548276",
                "name": "Team Space",
                "access": true
            },
            "archived": false,
            "override_statuses": false,
            "permission_level": "create"
        },
        {
            "id": "901510965734",
            "name": "my new list",
            "orderindex": 2,
            "content": "",
            "status": null,
            "priority": null,
            "assignee": null,
            "task_count": 0,
            "due_date": null,
            "start_date": null,
            "folder": {
                "id": "90156853247",
                "name": "test ID folder",
                "hidden": false,
                "access": true
            },
            "space": {
                "id": "90154548276",
                "name": "Team Space",
                "access": true
            },
            "archived": false,
            "override_statuses": false,
            "permission_level": "create"
        },
        {
            "id": "901510967044",
            "name": "another list by Postman",
            "orderindex": 3,
            "content": "",
            "status": null,
            "priority": null,
            "assignee": null,
            "task_count": 0,
            "due_date": null,
            "start_date": null,
            "folder": {
                "id": "90156853247",
                "name": "test ID folder",
                "hidden": false,
                "access": true
            },
            "space": {
                "id": "90154548276",
                "name": "Team Space",
                "access": true
            },
            "archived": false,
            "override_statuses": false,
            "permission_level": "create"
        },
        {
            "id": "901511294077",
            "name": "Eda",
            "orderindex": 4,
            "content": "",
            "status": null,
            "priority": null,
            "assignee": null,
            "task_count": 0,
            "due_date": null,
            "start_date": null,
            "folder": {
                "id": "90156853247",
                "name": "test ID folder",
                "hidden": false,
                "access": true
            },
            "space": {
                "id": "90154548276",
                "name": "Team Space",
                "access": true
            },
            "archived": false,
            "override_statuses": false,
            "permission_level": "create"
        },
        {
            "id": "901511294235",
            "name": "Sterling",
            "orderindex": 5,
            "content": "",
            "status": null,
            "priority": null,
            "assignee": null,
            "task_count": 0,
            "due_date": null,
            "start_date": null,
            "folder": {
                "id": "90156853247",
                "name": "test ID folder",
                "hidden": false,
                "access": true
            },
            "space": {
                "id": "90154548276",
                "name": "Team Space",
                "access": true
            },
            "archived": false,
            "override_statuses": false,
            "permission_level": "create"
        },
        {
            "id": "901511294301",
            "name": "Hayley",
            "orderindex": 6,
            "content": "",
            "status": null,
            "priority": null,
            "assignee": null,
            "task_count": 0,
            "due_date": null,
            "start_date": null,
            "folder": {
                "id": "90156853247",
                "name": "test ID folder",
                "hidden": false,
                "access": true
            },
            "space": {
                "id": "90154548276",
                "name": "Team Space",
                "access": true
            },
            "archived": false,
            "override_statuses": false,
            "permission_level": "create"
        },
        {
            "id": "901511321603",
            "name": "someName1",
            "orderindex": 7,
            "content": "",
            "status": null,
            "priority": null,
            "assignee": null,
            "task_count": 0,
            "due_date": null,
            "start_date": null,
            "folder": {
                "id": "90156853247",
                "name": "test ID folder",
                "hidden": false,
                "access": true
            },
            "space": {
                "id": "90154548276",
                "name": "Team Space",
                "access": true
            },
            "archived": false,
            "override_statuses": false,
            "permission_level": "create"
        },
        {
            "id": "901511321470",
            "name": "someName",
            "orderindex": 8,
            "content": "",
            "status": null,
            "priority": null,
            "assignee": null,
            "task_count": 0,
            "due_date": null,
            "start_date": null,
            "folder": {
                "id": "90156853247",
                "name": "test ID folder",
                "hidden": false,
                "access": true
            },
            "space": {
                "id": "90154548276",
                "name": "Team Space",
                "access": true
            },
            "archived": false,
            "override_statuses": false,
            "permission_level": "create"
        },
        {
            "id": "901511322120",
            "name": "t",
            "orderindex": 9,
            "content": "",
            "status": null,
            "priority": null,
            "assignee": null,
            "task_count": 0,
            "due_date": null,
            "start_date": null,
            "folder": {
                "id": "90156853247",
                "name": "test ID folder",
                "hidden": false,
                "access": true
            },
            "space": {
                "id": "90154548276",
                "name": "Team Space",
                "access": true
            },
            "archived": false,
            "override_statuses": false,
            "permission_level": "create"
        },
        {
            "id": "901511330723",
            "name": "Lorenz",
            "orderindex": 10,
            "content": "",
            "status": null,
            "priority": null,
            "assignee": null,
            "task_count": 0,
            "due_date": null,
            "start_date": null,
            "folder": {
                "id": "90156853247",
                "name": "test ID folder",
                "hidden": false,
                "access": true
            },
            "space": {
                "id": "90154548276",
                "name": "Team Space",
                "access": true
            },
            "archived": false,
            "override_statuses": false,
            "permission_level": "create"
        },
        {
            "id": "901511330726",
            "name": "p",
            "orderindex": 11,
            "content": "",
            "status": null,
            "priority": null,
            "assignee": null,
            "task_count": 0,
            "due_date": null,
            "start_date": null,
            "folder": {
                "id": "90156853247",
                "name": "test ID folder",
                "hidden": false,
                "access": true
            },
            "space": {
                "id": "90154548276",
                "name": "Team Space",
                "access": true
            },
            "archived": false,
            "override_statuses": false,
            "permission_level": "create"
        },
        {
            "id": "901511338443",
            "name": "new text",
            "orderindex": 12,
            "content": "",
            "status": null,
            "priority": null,
            "assignee": null,
            "task_count": 0,
            "due_date": null,
            "start_date": null,
            "folder": {
                "id": "90156853247",
                "name": "test ID folder",
                "hidden": false,
                "access": true
            },
            "space": {
                "id": "90154548276",
                "name": "Team Space",
                "access": true
            },
            "archived": false,
            "override_statuses": false,
            "permission_level": "create"
        },
        {
            "id": "901511339087",
            "name": "text string",
            "orderindex": 13,
            "content": "",
            "status": null,
            "priority": null,
            "assignee": null,
            "task_count": 0,
            "due_date": null,
            "start_date": null,
            "folder": {
                "id": "90156853247",
                "name": "test ID folder",
                "hidden": false,
                "access": true
            },
            "space": {
                "id": "90154548276",
                "name": "Team Space",
                "access": true
            },
            "archived": false,
            "override_statuses": false,
            "permission_level": "create"
        },
        {
            "id": "901511339241",
            "name": "thgnymglh,g",
            "orderindex": 14,
            "content": "",
            "status": null,
            "priority": null,
            "assignee": null,
            "task_count": 0,
            "due_date": null,
            "start_date": null,
            "folder": {
                "id": "90156853247",
                "name": "test ID folder",
                "hidden": false,
                "access": true
            },
            "space": {
                "id": "90154548276",
                "name": "Team Space",
                "access": true
            },
            "archived": false,
            "override_statuses": false,
            "permission_level": "create"
        },
        {
            "id": "901511339379",
            "name": "thguhgy,l,jl,g",
            "orderindex": 15,
            "content": "",
            "status": null,
            "priority": null,
            "assignee": null,
            "task_count": 0,
            "due_date": null,
            "start_date": null,
            "folder": {
                "id": "90156853247",
                "name": "test ID folder",
                "hidden": false,
                "access": true
            },
            "space": {
                "id": "90154548276",
                "name": "Team Space",
                "access": true
            },
            "archived": false,
            "override_statuses": false,
            "permission_level": "create"
        },
        {
            "id": "901511344214",
            "name": "test post req",
            "orderindex": 16,
            "content": "",
            "status": null,
            "priority": null,
            "assignee": null,
            "task_count": 0,
            "due_date": null,
            "start_date": null,
            "folder": {
                "id": "90156853247",
                "name": "test ID folder",
                "hidden": false,
                "access": true
            },
            "space": {
                "id": "90154548276",
                "name": "Team Space",
                "access": true
            },
            "archived": false,
            "override_statuses": false,
            "permission_level": "create"
        },
        {
            "id": "901511344967",
            "name": "testdffybkyungiuq",
            "orderindex": 17,
            "content": "",
            "status": null,
            "priority": null,
            "assignee": null,
            "task_count": 0,
            "due_date": null,
            "start_date": null,
            "folder": {
                "id": "90156853247",
                "name": "test ID folder",
                "hidden": false,
                "access": true
            },
            "space": {
                "id": "90154548276",
                "name": "Team Space",
                "access": true
            },
            "archived": false,
            "override_statuses": false,
            "permission_level": "create"
        },
        {
            "id": "901511448394",
            "name": "Ralph",
            "orderindex": 18,
            "content": "",
            "status": null,
            "priority": null,
            "assignee": null,
            "task_count": 0,
            "due_date": null,
            "start_date": null,
            "folder": {
                "id": "90156853247",
                "name": "test ID folder",
                "hidden": false,
                "access": true
            },
            "space": {
                "id": "90154548276",
                "name": "Team Space",
                "access": true
            },
            "archived": false,
            "override_statuses": false,
            "permission_level": "create"
        },
        {
            "id": "901511508130",
            "name": "Janae",
            "orderindex": 19,
            "content": "",
            "status": null,
            "priority": null,
            "assignee": null,
            "task_count": 0,
            "due_date": null,
            "start_date": null,
            "folder": {
                "id": "90156853247",
                "name": "test ID folder",
                "hidden": false,
                "access": true
            },
            "space": {
                "id": "90154548276",
                "name": "Team Space",
                "access": true
            },
            "archived": false,
            "override_statuses": false,
            "permission_level": "create"
        },
        {
            "id": "901511508178",
            "name": "Abagail",
            "orderindex": 20,
            "content": "",
            "status": null,
            "priority": null,
            "assignee": null,
            "task_count": 0,
            "due_date": null,
            "start_date": null,
            "folder": {
                "id": "90156853247",
                "name": "test ID folder",
                "hidden": false,
                "access": true
            },
            "space": {
                "id": "90154548276",
                "name": "Team Space",
                "access": true
            },
            "archived": false,
            "override_statuses": false,
            "permission_level": "create"
        },
        {
            "id": "901511508179",
            "name": "h",
            "orderindex": 21,
            "content": "",
            "status": null,
            "priority": null,
            "assignee": null,
            "task_count": 0,
            "due_date": null,
            "start_date": null,
            "folder": {
                "id": "90156853247",
                "name": "test ID folder",
                "hidden": false,
                "access": true
            },
            "space": {
                "id": "90154548276",
                "name": "Team Space",
                "access": true
            },
            "archived": false,
            "override_statuses": false,
            "permission_level": "create"
        },
        {
            "id": "901511618650",
            "name": "w",
            "orderindex": 30,
            "content": "",
            "status": null,
            "priority": null,
            "assignee": null,
            "task_count": 0,
            "due_date": null,
            "start_date": null,
            "folder": {
                "id": "90156853247",
                "name": "test ID folder",
                "hidden": false,
                "access": true
            },
            "space": {
                "id": "90154548276",
                "name": "Team Space",
                "access": true
            },
            "archived": false,
            "override_statuses": false,
            "permission_level": "create"
        },
        {
            "id": "901511651677",
            "name": "q",
            "orderindex": 31,
            "content": "",
            "status": null,
            "priority": null,
            "assignee": null,
            "task_count": 0,
            "due_date": null,
            "start_date": null,
            "folder": {
                "id": "90156853247",
                "name": "test ID folder",
                "hidden": false,
                "access": true
            },
            "space": {
                "id": "90154548276",
                "name": "Team Space",
                "access": true
            },
            "archived": false,
            "override_statuses": false,
            "permission_level": "create"
        },
        {
            "id": "901511656953",
            "name": "1",
            "orderindex": 32,
            "content": "",
            "status": null,
            "priority": null,
            "assignee": null,
            "task_count": 0,
            "due_date": null,
            "start_date": null,
            "folder": {
                "id": "90156853247",
                "name": "test ID folder",
                "hidden": false,
                "access": true
            },
            "space": {
                "id": "90154548276",
                "name": "Team Space",
                "access": true
            },
            "archived": false,
            "override_statuses": false,
            "permission_level": "create"
        }
    ]
}